spring:
  application:
    name: product-catalog-service
    kafka:
        config:
          partitions: 3
          replicas: 1

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_product_catalog
    username: ms_product_catalog_user
    password: 'H4rd-2GuezS#PDS_DB!'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    validate-migration-naming: true
    enabled: true
  kafka:
    bootstrap-servers: localhost:29092


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    non-secure-port: 80
    metadata-map:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    lease-renewal-interval-in-seconds: 5
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: ${vcap.services.pwa-eureka-service.credentials.uri}/eureka/

server:
  port: 8081
